default_config:

homeassistant:
  external_url: https://home-doamaral.duckdns.org
  customize: !include customize.yaml
tts:
  - platform: google_translate

influxdb:
  api_version: 2
  host: !secret influxdb_host
  port: 443
  token: !secret influxdb_token
  organization: Heaume
  bucket: HomeAssistant
  tags:
    source: HA
  exclude:
    entity_globs: "*"

speedtestdotnet:
  scan_interval:
    minutes: 10

sensor:
  - platform: systemmonitor
    scan_interval: 600
    resources:
      - type: disk_use_percent
        arg: /home
      - type: processor_temperature
  - platform: influxdb
    scan_interval: 600
    api_version: 2
    host: !secret influxdb_host
    port: 443
    organization: Heaume
    bucket: Plant
    token: !secret influxdb_token
    queries_flux:
      - name: "Humidité de Veggie"
        unit_of_measurement: "%"
        query: >
          filter(fn: (r) => r._measurement == "veggie")
          |> sort(columns: ["_time"], desc: true)
          |> limit(n: 1)
        range_start: "-1d"
  - platform: template
    sensors:
    #----- Count Automations
      count_automations:
        entity_id: sensor.date
        value_template: "{{ states.automation | list | length }}"
    #----- Count Scripts
      count_scripts:
        entity_id: sensor.date
        value_template: "{{ states.script| list | length }}"
    #----- Count Sensors
      count_sensors:
        entity_id: sensor.date
        value_template: "{{ states.sensor | list | length }}"
    #----- Count Switches
      count_switches:
        entity_id: sensor.date
        value_template: "{{ states.switch | list | length }}"
    #----- Count Zones
      count_zones:
        entity_id: sensor.date
        value_template: "{{ states.zone | list | length }}"


http:
    ssl_certificate: /ssl/fullchain.pem
    ssl_key: /ssl/privkey.pem

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
