---
title: Heaume

decluttering_templates: !include_dir_named www/lovelace/decluttering_templates

views:
  - !include www/lovelace/views/00_home_view.yaml
  - !include www/lovelace/views/01_server_view.yaml
  - !include www/lovelace/views/02_dylan_view.yaml
  - !include www/lovelace/views/03_battery_view.yaml
