---
id: server_hot
alias: Me notifier quand le serveur est trop chaud
description: ''
trigger:
  - platform: numeric_state
    entity_id: sensor.processor_temperature
    above: '60'
condition: []
action:
  - service: notify.mobile_app_iphone_de_dylan
    data:
      message: >
        🔥 Le serveur home assistant à dépasser les {{ trigger.above }}°C
      target: 3ff7d6cf4ed18895abe56a78c74faab4
