---
id: update_ha_available
alias: Nouvelle version de home assistant
trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: "off"
    to: "on"
action:
  - service: notify.mobile_app_iphone_de_dylan
    data:
      message: >
        🏠 La version {{ state_attr('binary_sensor.updater', 'newest_version') }}
        de home assistant est disponible.
      target: 3ff7d6cf4ed18895abe56a78c74faab4
