---
id: update_hacs_available
alias: Nouvelle version de home assistant community store
trigger:
  - platform: state
    entity_id: sensor.hacs
condition:
  - condition: template
    value_template: "{{ states('sensor.hacs') != 'unknown'}}"
  - condition: template
    value_template: "{{ (states('sensor.hacs') | float) != 0}}"
action:
  - service: notify.mobile_app_iphone_de_dylan
    data:
      message: >
        🏠 Home assistant community store a des mises à jours disponibles:
        {% for repo in state_attr('sensor.hacs', 'repositories') %}

        - {{ repo.display_name }} est disponible en version
        {{ repo["available_version"] }}.
        {% endfor %}
      target: 3ff7d6cf4ed18895abe56a78c74faab4
