---
id: automation_dylan_bedroom_light_off_light
alias: Etteindre les lumières de la chambre de Dylan quand lumineux.
description: "Turn off my hue light automatically when light."
trigger:
  - platform: numeric_state
    entity_id: sensor.hue_motion_sensor_1_light_level
    above: 40
condition:
  condition: and
  conditions:
    - condition: or
      conditions:
        - condition: state
          entity_id: light.hue_white_lamp_1
          state: "on"
        - condition: state
          entity_id: light.hue_white_lamp_3
          state: "on"
action:
  - service: light.turn_off
    target:
      entity_id:
        - group.bedroom_dylan_light
