---
id: automation_dylan_bedroom_light_on_lux
alias: Allumer les lumières de la chambre de Dylan quand sombre.
description: "Turn on my hue light automatically when dark."
trigger:
  - platform: numeric_state
    entity_id: sensor.hue_motion_sensor_1_light_level
    below: 100
condition:
  condition: and
  conditions:
    - condition: or
      conditions:
        - condition: state
          entity_id: light.hue_white_lamp_1
          state: "off"
        - condition: state
          entity_id: light.hue_white_lamp_3
          state: "off"
    - condition: state
      entity_id: binary_sensor.hue_motion_sensor_1_motion
      state: "on"
    - condition: time
      before: "21:30:00"
      after: "10:00:00"
action:
  - service: light.turn_on
    target:
      entity_id:
        - group.bedroom_dylan_light
    data:
      brightness: 255
